#!/bin/sh
echo "content-type: text/html"
echo

kubectl get namespaces -A > namespaces.html

cat << EOF
<html lang="pt-br">
<head>
    <meta charset=UTF-8>
    <meta http-equiv='X-UA-Compatible' content='IE=edge'>
    <meta name='viewport' content='width=device-width, initial-scale=1.0'>
    <title>Namespaces</title>
</head>
<body>
    <div>
        <h1>
            Namespaces
        </h1>
        <h3>
            Lista de namespaces atualmente presentes no cluster:
        </h3>
        <pre>
            $(cat ./namespaces.html)
        </pre>
        <footer>
            Última atualização - $(date +'%d/%m/%Y às %H:%M:%S').
        </footer>
    </div>
</body>
</html>
EOF